[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
token_program = "HCWnGf6fEuaaSrYFTJoydHoJ4JtDesqtR3tWV5hSsCc7"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/guild-audits/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
